import type { NextPage } from 'next';
import Head from 'next/head';
import AppHeader from '../../../components/ui-components/AppHeader';
import { ErrorBoundary } from '../../../components/ErrorBoundary';
import AppCard from '../../../components/ui-components/AppCard';
import PropertySelection from '../../../components/part-holder/PropertySelection';
import { useState } from 'react';
import clsx from 'clsx';

const App: NextPage = () => {
    const [hasBgImage, setHasBgImage] = useState(false);
    const handleHasBgImage = (hasBgImg: boolean) => {
        setHasBgImage(hasBgImg);
    };

    return (
        <>
            <Head>
                <title>Ground One</title>
                {/* <meta name="Ground One" content="Generated by create next app" /> */}
            </Head>
            <div
                className={clsx(
                    'min-h-screen',
                    !hasBgImage && 'bg-gradient-to-b from-[#5E7C9665] to-[#B2C7D145] pl-[calc(100vw-100%)]'
                )}
            >
                {' '}
                <ErrorBoundary scope="account.tsx">
                    <AppHeader
                        buttons={[
                            { name: 'BUY', url: '/part-holder/buy' },
                            { name: 'ACCOUNT', url: '/part-holder/account' },
                        ]}
                    />
                    <PropertySelection hasBgImage={handleHasBgImage} />
                </ErrorBoundary>
            </div>
        </>
    );
};

export default App;
