import type { NextPage } from 'next';
import Head from 'next/head';
import AppHeader from '../../../components/ui-components/AppHeader';
import { ErrorBoundary } from '../../../components/ErrorBoundary';
import AppCard from '../../../components/ui-components/AppCard';
import BuyPart from '../../../components/part-holder/BuyPart';
import BuyPartConfirm from '../../../components/part-holder/BuyPartConfirm';

const App: NextPage = () => {
    return (
        <>
            <Head>
                <title>Ground One</title>
                {/* <meta name="Ground One" content="Generated by create next app" /> */}
            </Head>
            <div className="min-h-screen from-[#5E7C9665] to-[#B2C7D145] pl-[calc(100vw-100%)] [&>:not(img)]:bg-gradient-to-b">
                <ErrorBoundary scope="buy/confirm.tsx">
                    <AppHeader
                        buttons={[
                            { name: 'BUY', url: '/part-holder/buy' },
                            { name: 'ACCOUNT', url: '/part-holder/account' },
                        ]}
                    />
                    <BuyPartConfirm />
                </ErrorBoundary>
            </div>
        </>
    );
};

export default App;
