import type { NextPage } from 'next';
import Head from 'next/head';
import AppHeader from '../../components/App/AppHeader';
import { ErrorBoundary } from '../../components/ErrorBoundary';

const App: NextPage = () => {
    return (
        <>
            <Head>
                <title>Ground One</title>
                {/* <meta name="Ground One" content="Generated by create next app" /> */}
            </Head>
            <div className="min-h-screen bg-gradient-to-b from-[#5E7C9665] to-[#B2C7D145]">
                <ErrorBoundary scope="buy.tsx">
                    <AppHeader
                        buttons={[
                            { name: 'BUY', url: '/buyer/buy' },
                            { name: 'ACCOUNT', url: '/buyer/account' },
                        ]}
                    />
                    <p>Buyer Buy</p>
                </ErrorBoundary>
            </div>
        </>
    );
};

export default App;
