import type { NextPage } from 'next';
import Head from 'next/head';
import AppHeader from '../src/components/App/AppHeader';
import ConnectWallet from '../src/components/App/ConnectWallet';
import CreatePart from '../src/components/App/CreatePart';
import WalletSample from '../src/components/App/WalletSample';

const App: NextPage = (props: any) => {
    return (
        <>
            <Head>
                <title>Ground One</title>
                {/* <meta name="Ground One" content="Generated by create next app" /> */}
                <link rel="icon" href="/favicon.ico" />
            </Head>
            <div className="min-h-screen bg-gradient-to-b from-[#5E7C9665] to-[#B2C7D145]">
                <AppHeader />
                <WalletSample />
                <CreatePart />
                <ConnectWallet />
            </div>
        </>
    );
};

export default App;
