import type { NextPage } from 'next';
import Head from 'next/head';
import HomepageHeader from '../src/components/homepage/HomepageHeader';
import Hero from '../src/components/homepage/Hero';
import StepOne from '../src/components/homepage/StepOne';
import StepTwo from '../src/components/homepage/StepTwo';
import { ErrorBoundary } from '../src/components/ErrorBoundary';

const Home: NextPage = (props: any) => {
    return (
        <>
            <Head>
                <title>Ground One</title>
                {/* <meta name="Ground One" content="Generated by create next app" /> */}
            </Head>
            <div>
                <ErrorBoundary scope="index.tsx">
                    <HomepageHeader />
                    <Hero />
                    <StepOne />
                    <StepTwo />
                </ErrorBoundary>
            </div>
        </>
    );
};

export default Home;
