import type { NextPage } from 'next';
import Head from 'next/head';
import HomepageHeader from '../src/components/Homepage/HomepageHeader';
import Hero from '../src/components/Homepage/Hero';
import StepOne from '../src/components/Homepage/StepOne';
import StepTwo from '../src/components/Homepage/StepTwo';

const Home: NextPage = (props: any) => {
    return (
        <>
            <Head>
                <title>Ground One</title>
                {/* <meta name="Ground One" content="Generated by create next app" /> */}
                <link rel="icon" href="/favicon.ico" />
            </Head>
            <div>
                <HomepageHeader />
                <Hero />
                <StepOne />
                <StepTwo />
            </div>
        </>
    );
};

export default Home;
