import type { NextPage } from 'next';
import Head from 'next/head';
import AppHeader from '../../components/App/AppHeader';
import { ErrorBoundary } from '../../components/ErrorBoundary';
import CreatePVT from '../../components/App/CreatePVT';

const App: NextPage = () => {
    return (
        <>
            <Head>
                <title>Ground One</title>
                {/* <meta name="Ground One" content="Generated by create next app" /> */}
            </Head>
            <div className="min-h-screen bg-gradient-to-b from-[#5E7C9665] to-[#B2C7D145]">
                <ErrorBoundary scope="create-pvt.tsx">
                    <AppHeader
                        buttons={[
                            { name: 'CREATE', url: '/creator/create-part' },
                            { name: 'MANAGE', url: '/creator/manage-part' },
                            { name: 'TEST', url: '/creator/create-pvt' },
                        ]}
                    />
                    <CreatePVT />
                </ErrorBoundary>
            </div>
        </>
    );
};

export default App;
