import type { NextPage } from 'next';
import Head from 'next/head';
import { ErrorBoundary } from '../components/ErrorBoundary';
import Hero from '../components/Homepage/Hero';
import HomepageHeader from '../components/Homepage/HomepageHeader';
import StepOne from '../components/Homepage/StepOne';
import StepTwo from '../components/Homepage/StepTwo';
import { ProductionHomepageGuard } from '../route-guards/ProductionHomepageGuard';

const Home: NextPage = () => {
    return (
        <>
            <Head>
                <title>Ground One</title>
                {/* <meta name="Ground One" content="Generated by create next app" /> */}
            </Head>
            <div>
                <ErrorBoundary scope="index.tsx">
                    <ProductionHomepageGuard>
                        <HomepageHeader />
                        <Hero />
                        <StepOne />
                        <StepTwo />
                    </ProductionHomepageGuard>
                </ErrorBoundary>
            </div>
        </>
    );
};

export default Home;
